import mongoose from "mongoose";

const documentSchema = new mongoose.Schema(
  {
    // Reference to user (Clerk)
    clerkUserId: {
      type: String,
      required: true,
      index: true
    },

    // Optional link to profile
    profileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Profile"
    },

    // Document metadata
    title: {
      type: String,
      required: true
    },

    documentType: {
      type: String,
      enum: [
        "lab_report",
        "prescription",
        "scan",
        "discharge_summary",
        "doctor_note",
        "other"
      ],
      default: "other"
    },

    // File storage details
    fileUrl: {
      type: String,
      required: true
    },

    fileType: {
      type: String,
      required: true
    },

    fileSize: {
      type: Number // in KB or MB
    },

    // AI related fields
    extractedText: {
      type: String
    },

    aiSummary: {
      type: String
    },

    // Health relevance tags (generated by AI)
    tags: [
      {
        type: String
      }
    ],

    // Report date (if present in document)
    reportDate: {
      type: Date
    },

    // Status
    processingStatus: {
      type: String,
      enum: ["uploaded", "processing", "completed", "failed"],
      default: "uploaded"
    }
  },
  {
    timestamps: true
  }
);

export default mongoose.model("Document", documentSchema);
